use std::fmt::Write as _;
use std::path::Path;

/// Scan `prompt-templates/` at the repo root and bake every file into the binary as a
/// `Template` table (see `src/templates.rs`). Compiling them in is what makes "drop a
/// file in the folder, `/release`" the whole workflow for adding a template: no bundle
/// resource, no `fs:` capability, and no runtime directory to keep in sync between
/// `tauri dev` and the shipped .app.
///
/// The generated `id` is the file name with everything outside `[A-Za-z0-9._-]` replaced
/// by `_`. It MUST stay colon-free: the row menu encodes item ids as
/// `pf-row:<action>:<window>:<node>` and `lib.rs` parses them with `splitn(4, ':')`, so a
/// colon anywhere in the action would misroute the event to a nonexistent window label,
/// where `emit_to` silently no-ops. APFS allows `:` in a file name, so this is a real
/// case rather than a theoretical one.
fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../prompt-templates");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut found: Vec<(String, String, String)> = Vec::new(); // (id, display, file name)
    match std::fs::read_dir(&dir) {
        Ok(entries) => {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                if name.starts_with('.') {
                    continue;
                }
                match entry.metadata() {
                    Ok(m) if m.is_file() && m.len() <= 256 * 1024 => {}
                    _ => continue,
                }
                // Non-UTF-8 can't be an `include_str!`, and a prompt is text by definition.
                if std::fs::read_to_string(entry.path()).is_err() {
                    continue;
                }
                println!("cargo:rerun-if-changed={}", entry.path().display());
                found.push((sanitize(&name), display_name(&name), name));
            }
        }
        Err(_) => println!(
            "cargo:warning=prompt-templates/ not found at {} — the Prompt Templates submenu will be empty",
            dir.display()
        ),
    }

    // Stable, filesystem-order-independent: by display name, case-insensitively.
    found.sort_by(|a, b| a.1.to_lowercase().cmp(&b.1.to_lowercase()).then(a.0.cmp(&b.0)));
    let mut ids: Vec<&String> = found.iter().map(|f| &f.0).collect();
    ids.sort();
    for pair in ids.windows(2) {
        assert_ne!(pair[0], pair[1], "prompt-templates: two files collapse to the same id");
    }

    let mut src = String::from(
        "// @generated by build.rs from prompt-templates/ — do not edit.\n\
         pub static TEMPLATES: &[Template] = &[\n",
    );
    for (id, display, name) in &found {
        let _ = writeln!(
            src,
            "    Template {{ id: {:?}, default_name: {:?}, body: include_str!({:?}) }},",
            id,
            display,
            dir.join(name).to_string_lossy()
        );
    }
    src.push_str("];\n");

    let out = Path::new(&std::env::var("OUT_DIR").unwrap()).join("templates_generated.rs");
    std::fs::write(&out, src).expect("write templates_generated.rs");

    tauri_build::build()
}

fn sanitize(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// `New-Feature-Discuss-Plan` -> `New Feature Discuss Plan`. Purely the DEFAULT: any
/// template can be renamed in Settings, and that override lives in the backend settings
/// table because the Rust menu builder is what has to read it.
fn display_name(name: &str) -> String {
    let stem = [".md", ".markdown", ".txt"]
        .iter()
        .find_map(|ext| name.strip_suffix(ext))
        .unwrap_or(name);
    let spaced: String = stem
        .chars()
        .map(|c| if c == '-' || c == '_' { ' ' } else { c })
        .collect();
    let trimmed = spaced.trim();
    if trimmed.chars().count() > 48 {
        trimmed.chars().take(48).collect::<String>().trim_end().to_string()
    } else {
        trimmed.to_string()
    }
}
